"""Generate src/CFTools/Strings/<culture>/Resources.resw from i18n/<lang>.txt.

    python scripts/build-resw.py

i18n/<lang>.txt holds one `Key=Value` per line (`#` comments, `\n` = line break).
`Key.Property` names bind to XAML x:Uid; plain keys are read from code via Loc.
The resw files are committed (the build needs them without Python), so run this
after every edit of i18n/*.txt and commit both.
"""

from __future__ import annotations

import sys
from pathlib import Path
from xml.sax.saxutils import escape

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "i18n"
OUT = ROOT / "src" / "CFTools" / "Strings"

# i18n file → MRT resource culture folder (zh needs the script subtag, pt the region)
CULTURES = {
    "en": "en-US",
    "ru": "ru",
    "de": "de",
    "fr": "fr",
    "es": "es",
    "it": "it",
    "pt-br": "pt-BR",
    "ja": "ja",
    "ko": "ko",
    "zh-cn": "zh-Hans",
    "pl": "pl",
    "tr": "tr",
}

HEADER = """<?xml version="1.0" encoding="utf-8"?>
<root>
  <!-- GENERATED by scripts/build-resw.py from i18n/{lang}.txt — edit the .txt, not this file. -->
  <resheader name="resmimetype"><value>text/microsoft-resx</value></resheader>
  <resheader name="version"><value>2.0</value></resheader>
  <resheader name="reader"><value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value></resheader>
  <resheader name="writer"><value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value></resheader>
"""


def parse(path: Path) -> dict[str, str]:
    entries: dict[str, str] = {}
    for n, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        line = raw.rstrip("\r")
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        if "=" not in line:
            sys.exit(f"{path.name}:{n}: expected Key=Value")
        key, value = line.split("=", 1)
        key = key.strip()
        if key in entries:
            sys.exit(f"{path.name}:{n}: duplicate key {key}")
        entries[key] = value.replace("\\n", "\n")
    return entries


def write_resw(lang: str, culture: str, entries: dict[str, str]) -> Path:
    folder = OUT / culture
    folder.mkdir(parents=True, exist_ok=True)
    target = folder / "Resources.resw"
    body = [HEADER.format(lang=lang)]
    for key, value in entries.items():
        body.append(f'  <data name="{escape(key, {chr(34): "&quot;"})}" xml:space="preserve">\n    <value>{escape(value)}</value>\n  </data>\n')
    body.append("</root>\n")
    target.write_text("".join(body), encoding="utf-8", newline="\n")
    return target


def main() -> int:
    written = 0
    for lang, culture in CULTURES.items():
        path = SRC / f"{lang}.txt"
        if not path.exists():
            print(f"skip {lang}: {path} missing")
            continue
        target = write_resw(lang, culture, parse(path))
        written += 1
        print(f"{lang:6} -> {target.relative_to(ROOT)}")
    print(f"{written} resw file(s) written")
    return 0


if __name__ == "__main__":
    sys.exit(main())
